synsets_manual = [['ahad', 'minggu'],
                  ['ahad', 'esa', 'satu', 'tunggal'],
                  ['setanggi'],
                  ['aborsi', 'pengangguran'],
                  ['pasar', 'pekan', 'rekan'],
                  ['minggu', 'pekan'],
                  ['abu', 'duli', 'lebu'],
                  ['peci', 'kopiah', 'songkok'],
                  ['harian', 'koran', 'surat kabar'],
                  ['susur'],
                  ['temu', 'jumpa'],
                  ['suar', 'pijar'],
                  ['suar'],
                  ['lilin', 'parafin'],
                  ['benalu', 'parasit', 'sakat'],
                  ['binatang', 'hewan', 'satwa'],
                  ['fantasi', 'fiksi'],
                  ['lamur', 'rabun'],
                  ['perkakas', 'radas'],
                  ['persentase'],
                  ['bandrek', 'serbuk']]