synsets_lower = [
    [[['ahad', 'minggu']], [['ahad', 'esa', 'satu', 'tunggal']]],
    [['kemenyan', 'setanggi']],
    [[['aborsi', 'pengguguran']]],
    [[['pasar', 'pekan', 'rekan']], [['minggu', 'pekan']]],
    [[['abu', 'debu', 'duli', 'lebu', 'serdak']]],
    [[['abu', 'abuk', 'bubuk', 'debu', 'duli', 'lebu', 'serbuk', 'tepung']]],
    [[['kopiah', 'peci', 'songkok']]],
    [[['harian', 'koran', 'surat kabar']]],
    [['sugi', 'susur']],
    [[['jumpa', 'sua', 'temu']]],
    [[["marak", 'pijar', 'suar']], ['suar', 'menara api', 'mercusuar', 'rumah api']],
    [[['lilin', 'parafin']]],
    [[['benalu', 'parasit', 'sakat']]],
    [[['binatang', 'hewan', 'satwa']]],
    [[['binatang', 'dabat', 'fauna', 'hewan', 'satwa']]],
    [[['fantasi', 'fiksi', 'khayalan', 'lamunan']]],
    [[['cadok', 'lamur', 'rabun']]],
    [[['alat', 'perkakas', 'radas']]],
    [['bagian', 'persentase']],
    [[['bandrek', 'serbat']]],
    [[['ahad', 'minggu', 'pekan']]],
    [[['ahad', 'esa', 'satu', 'tunggal']]],
    [[['aborsi', 'pengguguran']]],
    [[['pasar', 'pekan', 'rekan']]],
    [[['pasar', 'pekan', 'rekan']]],
    [[['kopiah', 'peci', 'songkok']]],
    [[['kopiah', 'peci', 'songkok']]],
    [[['lilin', 'parafin']]],
    [[['benalu', 'parasit', 'pasilan', 'sakat']]],
    [[['bandrek', 'serbat']]]
]