synsets_manual = [
    [[['ahad', 'minggu']], [['ahad', 'esa', 'satu', 'tunggal']]],
    [['setanggi']],
    [[['aborsi', 'pengguguran']]],
    [[['pasar', 'pekan', 'rekan']], [['minggu', 'pekan']]],
    [[['abu', 'duli', 'lebu']]],
    [[['abu', 'abuk', 'debu'], ['abu', 'debu', 'duli'], ['abu', 'duli', 'lebu']]],
    [[['kopiah', 'peci', 'songkok']]],
    [[['harian', 'koran', 'surat kabar']]],
    [['susur']],
    [[['jumpa', 'temu']]],
    [[['pijar', 'suar']], ['suar']],
    [[['lilin', 'parafin']]],
    [[['benalu', 'parasit', 'sakat']]],
    [[['binatang', 'hewan', 'satwa']]],
    [[['binatang', 'hewan', 'satwa']]],
    [[['fantasi', 'fiksi']]],
    [[['lamur', 'rabun']]],
    [[['perkakas', 'radas']]],
    [['persentase']],
    [[['bandrek', 'serbat']]],
    [[['ahad', 'minggu'], ['minggu', 'pekan']]],
    [[['ahad', 'esa', 'satu', 'tunggal']]],
    [[['aborsi', 'pengguguran']]],
    [[['pasar', 'pekan', 'rekan']]],
    [[['pasar', 'pekan', 'rekan']]],
    [[['kopiah', 'peci', 'songkok']]],
    [[['kopiah', 'peci', 'songkok']]],
    [[['lilin', 'parafin']]],
    [[['benalu', 'parasit', 'pasilan'], ['benalu', 'parasit', 'sakat']]],
    [[['bandrek', 'serbat']]]
]