synsets_manual = [
    [['ahad', 'minggu'],['ahad', 'esa', 'satu', 'tunggal']],
    [['setanggi']],
    [['aborsi', 'pengangguran']],
    [['pasar', 'pekan', 'rekan'],['minggu', 'pekan']],
    [['abu', 'duli', 'lebu']],
    [['abu', 'duli', 'lebu']],
    [['peci', 'kopiah', 'songkok']],
    [['harian', 'koran', 'surat kabar']],
    [['susur']],
    [['temu', 'jumpa']],
    [['suar', 'pijar'],['suar']],
    [['lilin', 'parafin']],
    [['benalu', 'parasit', 'sakat']],
    [['binatang', 'hewan', 'satwa']],
    [['binatang', 'hewan', 'satwa']],
    [['fantasi', 'fiksi']],
    [['lamur', 'rabun']],
    [['perkakas', 'radas']],
    [['persentase']],
    [['bandrek', 'serbat']],
    [['minggu', 'pekan'],['ahad', 'minggu']],
    [['ahad', 'esa', 'satu', 'tunggal']],
    [['aborsi', 'pengangguran']],
    [['pasar', 'pekan', 'rekan']],
    [['pasar', 'pekan', 'rekan']],
    [['kopiah', 'peci', 'songkok']],
    [['kopiah', 'peci', 'songkok']],
    [['lilin', 'parafin']],
    [['benalu', 'parasit', 'pasilan']],
    [['bandrek', 'serbat']]
]